<a href="https://colab.research.google.com/github/sodiq-sulaimon/Preparations-for-TensorFlow-Developer-Certification/blob/main/Time_Series/Preparing_Time_Series_Features_and_Labels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

### Create a Simple dataset

In [2]:
dataset = tf.data.Dataset.range(10)

for val in dataset:
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


### Windowing the data

In [3]:
dataset = tf.data.Dataset.range(10)
window_dataset = dataset.window(size=5, shift=1)

for window_data in window_dataset:

  print([val.numpy() for val in window_data])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]
[6, 7, 8, 9]
[7, 8, 9]
[8, 9]
[9]


In [4]:
# Make the window of equal size
dataset = tf.data.Dataset.range(10)
window_dataset = dataset.window(size=5, shift=1, drop_remainder=True)

for window_data in window_dataset:

  print([val.numpy() for val in window_data])

[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]
[5, 6, 7, 8, 9]


### Flatten the windows

In [13]:
dataset = tf.data.Dataset.range(10)
window_dataset = dataset.window(size=5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
window_dataset = window_dataset.flat_map(lambda window: window.batch(5))

for window in window_dataset:
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


### Group into features and labels

In [14]:
dataset = tf.data.Dataset.range(10)
window_dataset = dataset.window(size=5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
window_dataset = window_dataset.flat_map(lambda window: window.batch(5))
window_dataset = window_dataset.map(lambda window: (window[:-1], window[-1]))

for x,y in window_dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())

x =  [0 1 2 3]
y =  4
x =  [1 2 3 4]
y =  5
x =  [2 3 4 5]
y =  6
x =  [3 4 5 6]
y =  7
x =  [4 5 6 7]
y =  8
x =  [5 6 7 8]
y =  9


### Shuffle the data

In [20]:
dataset = tf.data.Dataset.range(10)
window_dataset = dataset.window(size=5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
window_dataset = window_dataset.flat_map(lambda window: window.batch(5))
window_dataset = window_dataset.map(lambda window: (window[:-1], window[-1]))

window_dataset = window_dataset.shuffle(buffer_size=10)

for x,y in window_dataset:
  print("x = ", x.numpy())
  print("y = ", y.numpy())

x =  [4 5 6 7]
y =  8
x =  [3 4 5 6]
y =  7
x =  [2 3 4 5]
y =  6
x =  [5 6 7 8]
y =  9
x =  [0 1 2 3]
y =  4
x =  [1 2 3 4]
y =  5


### Create batches for training

In [21]:
dataset = tf.data.Dataset.range(10)
window_dataset = dataset.window(size=5, shift=1, drop_remainder=True)

# Flatten the windows by putting its elements in a single batch
window_dataset = window_dataset.flat_map(lambda window: window.batch(5))
window_dataset = window_dataset.map(lambda window: (window[:-1], window[-1]))

window_dataset = window_dataset.shuffle(buffer_size=10)

window_dataset = window_dataset.batch(2).prefetch(1)

for x,y in window_dataset:
  print("x = ", x.numpy())

  print("y = ", y.numpy())

x =  [[2 3 4 5]
 [1 2 3 4]]
y =  [6 5]
x =  [[4 5 6 7]
 [5 6 7 8]]
y =  [8 9]
x =  [[3 4 5 6]
 [0 1 2 3]]
y =  [7 4]


In [24]:
# Generate the dataset
data = tf.data.Dataset.range(20)

# Split it to windows
data = data.window(size=5, shift=1, drop_remainder=True)

# Flatten the windows
data = data.flat_map(lambda window: window.batch(5))

# Generate features and labels
data = data.map(lambda window: (window[:-1], window[-1]))

# Shuffle the data
data = data.shuffle(buffer_size=10)

# Create batches for training with prefetch
data = data.batch(2).prefetch(1)

# Print the result
for x,y in data:
  print("x = ", x.numpy())
  print("y =", y.numpy())


x =  [[ 8  9 10 11]
 [10 11 12 13]]
y = [12 14]
x =  [[3 4 5 6]
 [5 6 7 8]]
y = [7 9]
x =  [[ 9 10 11 12]
 [13 14 15 16]]
y = [13 17]
x =  [[14 15 16 17]
 [15 16 17 18]]
y = [18 19]
x =  [[ 0  1  2  3]
 [11 12 13 14]]
y = [ 4 15]
x =  [[2 3 4 5]
 [1 2 3 4]]
y = [6 5]
x =  [[12 13 14 15]
 [ 4  5  6  7]]
y = [16  8]
x =  [[ 7  8  9 10]
 [ 6  7  8  9]]
y = [11 10]
